### ISSUE TITLE
Add compact stat blocks without Foundry requirement

### ISSUE THREAD

**Issue by FusioN-Strider** [giffyglyph/giffyglyphs-monster-maker#1]
Those things look cool, but right now, they're essentially locked behind Foundry's paywall. 
Make a standalone version looking like the Foundry Stat Blocks to make them accessible to me. I mean, the public.

**Comment by TheDataReaper** [comment]
Hey after a bit of a break from coding Giff does have an update to the webapp planned that should have what your looking for.

**Comment by giffyglyph** [comment]
I've created a new repository for the monster maker webapp code, so will move this request there as https://github.com/giffyglyph/webapp-5e-monster-maker/issues/1.
